language: ruby
branches:
  only:
  - master
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
exclude:
- vendor
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: zAPHfGjimmMSUTECxMfausKz65cQcAOSyYu7rfxQWn/G20Cv+I4aEHaxY90VCfOJbTuFf21Tm1tIxIg99DPynWXACUC1dBWKul8P6VAPMRVouoEX4tJl90t74zYYb1OaGWVfwMEeTX4WZVMhYybD/Kwkvm7Za9LbrZns3RVSrsVedoeVWWp1wJLPzL3Zzmy1su+98PgY1iRL2e/aJikt0figP58V/JL9aeDQDJnZTEZ1KxM3r933jmVuErLFTqOwxUDXu9aM4PjKGAMDBMHsr/PTT8JWIDtahQtVxL0dtxK2F0Eq0MUWTtKputM8iPRiTAvw6cdQN7HH0zreWp0aWu+m803//m9rmO175HJXRieHYQmva2d7mM8ezD61jkBg38fxNiwxffnA1/uzPPaN2hkmK4Fta99h0WXE2N4mM0vThEtMXjz72ln6iJhDN/wwyAIeFuwrYRpqv7sOVGKA0CVkPg+6gNDUTyJDJwjHdV0eAUlQsrrsG0Mb8HtrSQCQd8jJr/ffNMfqD5BPvpk4TDozEuJoGD/ZLyd1nk1Zhs7e8B0XAqe9vBJRVXoX8jIw6nI2V7xGxjt2icL3XifzqGOND9xuBUEcXt9yVN/Kcnpa++6nFG+FP0CUbgrSWTxRW+yZ17zqnGTTqlbPiG2Hu8DCGtW8VOF2M91C+n54F0M=
sudo: false
token: ***REMOVED***
