language: ruby
cache: bundler
branches:
  only:
  - master
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
exclude:
- vendor
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: "mzD3fDBBQ1mD9n98Zfa2CrWl02jgDyHFyd9zwi5Cv02VmkZSJkT4HLamIpn0YFqb4RTlfIsy3374oEJX7tMb3cQzARlQZASrZHCS1HiPHIzgpVXbjE7d06R796Smot/X0Y839HwVCulTEhPvmgGpY4jtC0WX3d+lHW/iKxvTIujtn5VM95tbJku1b9caOKHOBiBBUMFhJmoyxf9Bufdrcbe+GCkF8a2VTH9OVAbmpTR1CelNU1UDKhV+paxzZkG9s3DXhHVqs1OmHybPRqPsxOK36RD29gdckqWA3OdhtH6XRQyTZFjzFFVorow+BGzdp1v4+c92cr+kVVfA8K8DVP9xL5/2erGC7UAw4724mes/lDOwejuDArplarvh1ELye/vZALcrNIaO8F597vy5E/c6iNec8ZuCUNig63EJKx4hFXxQgcOnkAjc7kZ5tGRZ3Im1n2ibevaLOFnItIYIlU3CzPtrT58lzNxp6uovy5D6dddyCteEApgJTFFaQlQGXDtXD7DF4soq8eXPf68qYWO9n2/By1LaGDTi3RcLfgXwfw6V8E/JrY7A8YRcXUUIZ6/LKKolX+mPexUxUcqWgTQ9wLRcHXlk1cmgV4DUdPW2BrTYZa0epIgjvvSMyNuENMQnAVXtf/y4rqOfmxDcaQhFycyCfJQgyCoK/auoGHY="
sudo: false
