#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi
set -e

startTravisFold() {
  taskName=$1
  echo "Build Task ${taskName}" && echo -en "travis_fold:start:script.build.${taskName}\\r"
  echo "start time ${taskName}" && echo -en "travis_time:start:${taskName}-time\\r"
  echo ''
  echo "${taskName}"

}

endTravisFold() {
  taskName=$1
  startTime=$2
  endTime=`date +%s%N`
  durationTime=`expr $endTime - $startTime`

  echo -en "travis_time:end:${taskName}-time:start=${startTime},finish=${endTime},duration=${durationTime}\\r"
  echo -en "travis_fold:end:script.build.${taskName}\\r"

}

siteInit() {
  echo '"Initialize publishing repo"' && echo -en 'travis_fold:start:script.build.site-init\\r'
  echo ''
  echo '"site-init"'

  rm -rf _site
  mkdir _site
  rm -rf _tmp_backup
  mkdir _tmp_backup

  git clone https://${GH_TOKEN}@github.com/k-rajan/k-rajan.github.io.git _site

  ### retains important files
  echo "Retaining CNAME, README,md, LICENSE from repo"
  cp _site/README.md _tmp_backup/
  cp _site/LICENSE _tmp_backup/
  cp _site/CNAME _tmp_backup/
  echo -en 'travis_fold:end:script.build.site-init\\r'
}

siteGen() {
  startTravisFold "site-gen"
  startTime=`date +%s%N`

  bundle exec jekyll build

  ### bring back
  echo "Copying retained files"
  cp _tmp_backup/* _site/

  endTravisFold "site-gen" "${startTime}"
}

siteTest() {
  echo '"Testing site"' && echo -en 'travis_fold:start:script.build.site-test\\r'
  echo ''
  echo '"site-test"'
  echo "Html proofer"
  bundle exec htmlproofer  ./_site  --allow_hash_href --assume_extension --disable-external
  echo -en 'travis_fold:end:script.build.site-test\\r'
}

siteDeploy() {
  echo '"Deploying site to github pages"' && echo -en 'travis_fold:start:script.build.site-deploy\\r'
  echo ''
  echo '"site-deploy"'

  cd _site
  git config user.email ${GIT_EMAIL}
  git config user.name ${GIT_NAME}
  git add --all
  git commit -a -m "Travis CI | site-generator | #$TRAVIS_BUILD_NUMBER"
  git show --name-only
  git push --force origin master

  echo -en 'travis_fold:end:script.build.site-deploy\\r'
}

###############################################################################
# sequence of steps are called here
###############################################################################
siteInit
siteGen
siteTest
siteDeploy